controllers:
    resource: ../src/Controller/
    type: annotation

kernel:
    resource: ../src/Kernel.php
    type: annotation

blog:
    path: /
    controller: App\Controller\TodoController::index
